apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmasa-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cloudmasa-server
  template:
    metadata:
      labels:
        app: cloudmasa-server
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.server.repository }}:{{ .Values.image.server.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "{{ .Values.env.MONGO_URI }}"
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
